eval_samples: 1496
hparams: /DepthPrior/object_detection/efficientdet/configs/train/allclasses_orig.yaml
infer_folder: /DepthPrior/datasets/KITTI/training/image_2/
infer_indices: /DepthPrior/datasets/KITTI/vaL_index_list.txt
model_dir: /DepthPrior/object_detection/efficientdet/models/trained_models/KITTI_depth_detection_inverse_minmax_expo_teacher10_V0
saved_model_dir: /DepthPrior/models/exported_models/SSL/EXP_KITTI_depth_detection_inverse_minmax_expo_teacher10_V0
val_file_pattern: /DepthPrior/datasets/KITTI/tf/_val.tfrecord
video_path: /DepthPrior/datasets/videos/xyz.mp4
