model: build/yolo11s.pt
data: "./dataset-configs/kitti.yaml"
pretrained: true
mlflow_tracking_uri: "sqlite:///runs/mlruns.db"
mlflow_experiment_name: "kitti"
device: 0
epochs: 400
batch: 128
imgsz: 640
runs_dir: "/runs/kitti"