model: yolo11s.yaml
pretrained: true
data: "./dataset-configs/sunrgbd2d.yaml"
mlflow_tracking_uri: "sqlite:///runs/mlruns.db"
mlflow_experiment_name: "sunrgbd2d"
device: 0
epochs: 400
batch: 128
imgsz: 640
runs_dir: "/runs/sunrgbd2d"