model: "/DepthPrior/object_detection/yolov11/build/yolo11s.pt"
pretrained: true
data: "/DepthPrior/object_detection/yolov11/dataset-configs/sunrgbd2d-subset.yaml"
mlflow_tracking_uri: "sqlite:///runs/mlruns.db"
mlflow_experiment_name: "sunrgbd2d-subset"
device: 0
epochs: 100
batch: 64
imgsz: 640
runs_dir: "/runs/sunrgbd2d-subset"