model: yolo11s.yaml
pretrained: true
data: "./dataset-configs/visdrone.yaml"
mlflow_tracking_uri: "sqlite:///runs/mlruns.db"
mlflow_experiment_name: "visdrone"
device: 0
epochs: 400
batch: 128
imgsz: 640
runs_dir: "/runs/visdrone"