eval_samples: 1496
hparams: /DepthPrior/object_detection/efficientdet/configs/train/allclasses_orig.yaml
model_dir: /DepthPrior/object_detection/efficientdet/models/trained_models/STAC/KITTI_STAC_student10_thr_09_score_V0
val_file_pattern: /DepthPrior/datasets/KITTI/tf/_val.tfrecord
depth_maps_folder: /DepthPrior/datasets/KITTI/depth_validation/